image: go1.3
env:
  - GOPATH=/var/cache/drone
script:
  - go get launchpad.net/gocheck
  - go get -v github.com/axw/gocov/gocov
  - go build
  - gocov test | gocov report
services:
  - redis
notify:
  email:
    recipients:
      - jarethdisley@hotmail.com
